config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "booths#index"
  resources :booths
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booth.rb
class Booth < ApplicationRecord

  with_options presence: true do
    validates :image, :prize_name, :machine_name, :category
  end

  belongs_to :user
  has_one_attached :image
  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_format_of :password, with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  with_options presence: true do
    validates :name, :occupation, :position
  end
  
  has_many :booths
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :occupation, :position])
  end
end

app/controllers/booths_controller.rb
class BoothsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destroy]

  def index
    @booths = Booth.all.order("id DESC")
  end

  def new
    @booth = Booth.new
  end

  def create
    @booth = Booth.new(booth_params)
    if @booth.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @booth = Booth.find(params[:id])
  end

  def edit
    @booth = Booth.find(params[:id])
  end
  
  def update
    @booth = Booth.find(params[:id])
    if @booth.update(booth_params)
      redirect_to booth_path(@booth)
    else
      render :edit
    end
  end

  def destroy
    @booth = Booth.find(params[:id])
    @booth.destroy
    redirect_to root_path
  end
  
  private

  def booth_params
    params.require(:booth).permit(:image, :prize_name, :machine_name, :category).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booths_helper.rb
module BoothsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/booths/_booth.html.erb
<div class="card">
  <%= link_to image_tag(booth.image, class: :card__img), booth_path(booth.id), method: :get %>
  <div class="card__body">
    <%= link_to booth.prize_name, booth_path(booth.id), method: :get, class: :card__title%>
    <p class="card__summary">
      <%= booth.machine_name %>
    </p>
    <p class="card__summary">
      <%= booth.category %>
    </p>
    <%= link_to "by#{booth.user.name}", "/users/#{booth.user_id}", class: :card__user %>
  </div>
</div>

app/views/booths/_form.html.erb
<%= form_with(model: booth, local: true) do |f|%>
  <div class="field">
    <%= f.label :prize_name, "景品名" %><br />
    <%= f.text_field :prize_name %>
  </div>

  <div class="field">
    <%= f.label :machine_name, "機械名" %><br />
    <%= f.text_area :machine_name, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :category, "カテゴリー" %><br />
    <%= f.text_area :category, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "ブースの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/booths/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ブース編集</h2>
      <%= render partial: "form", locals: { booth: @booth } %>
    </div>
  </div>
</div>

app/views/booths/index.html.erb
<main class="main">
  <div class="inner">
      <% if user_signed_in? %>
        <div class="greeting">
          こんにちは、
          <%= link_to current_user.name, "/users/#{current_user.id}", class: :greeting__link %>
          さん
        </div>
      <% end %>
    <div class="card__wrapper">
      <%= render partial: 'booth', collection: @booths %>
    </div>
  </div>
</main>

app/views/booths/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規ブース投稿</h2>
        <%= render partial: "form", locals: { booth: @booth } %>
    </div>
  </div>
</div>

app/views/booths/show.html.erb
<main class="main">
  <div class="inner">
    <div class="booth__wrapper">
      <p class="booth__hedding">
         <%= @booth.prize_name %>
      </p>
      <%= link_to "by#{@booth.user.name}", "/users/#{@booth.user_id}", class: :booth__user %>
      <% if user_signed_in? && current_user.id == @booth.user_id %>
        <div class="booth__manage">
          <%= link_to "編集する", edit_booth_path(@booth.id), method: :get, class: :booth__btn %>
          <%= link_to "削除する", booth_path(@booth.id), method: :delete, class: :booth__btn %>
        </div>
      <% end %>
      <div class="booth__image">
          <%= image_tag @booth.image, class: 'booth-image' %>
      </div>
      <div class="booth__body">
        <div class="booth__detail">
          <p class="detail__title">機械名</p>
          <p class="detail__message">
            <%= @booth.machine_name %>
          </p>
        </div>
        <div class="booth__detail">
          <p class="detail__title">カテゴリー</p>
          <p class="detail__message">
            <%= @booth.category %>
          </p>
        </div>
      </div>

    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BoothShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
          </div>
            <% if user_signed_in? %>
              <div class="nav__right">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
                <%= link_to "New Booth", new_booth_path, class: :nav__btn %>
              </div>
            <% else %>
              <div class="nav__right">
                <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
                <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
              </div>
            <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © BOOTH SHARE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのブース"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'booths/booth', collection: @user.booths %>
      </div>
    </div>
  </div>
</div>